// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFDXtpWcznlPfpftdbuFqhr3ZoNtqJrk',
    appId: '1:872011350851:web:76ed1965b0b305fe1e25f6',
    messagingSenderId: '872011350851',
    projectId: 'helloflutter-dd552',
    authDomain: 'helloflutter-dd552.firebaseapp.com',
    storageBucket: 'helloflutter-dd552.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnd4YF_9O8ZDMjeWTEG9McPOVpLj60GME',
    appId: '1:872011350851:android:bf340eaa1d0197bf1e25f6',
    messagingSenderId: '872011350851',
    projectId: 'helloflutter-dd552',
    storageBucket: 'helloflutter-dd552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjPlM7e8BcScg_860dO0B0tOgWmUk-kU',
    appId: '1:872011350851:ios:30e1d4a33a6cbea01e25f6',
    messagingSenderId: '872011350851',
    projectId: 'helloflutter-dd552',
    storageBucket: 'helloflutter-dd552.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjPlM7e8BcScg_860dO0B0tOgWmUk-kU',
    appId: '1:872011350851:ios:30e1d4a33a6cbea01e25f6',
    messagingSenderId: '872011350851',
    projectId: 'helloflutter-dd552',
    storageBucket: 'helloflutter-dd552.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFDXtpWcznlPfpftdbuFqhr3ZoNtqJrk',
    appId: '1:872011350851:web:87bb694914d008e01e25f6',
    messagingSenderId: '872011350851',
    projectId: 'helloflutter-dd552',
    authDomain: 'helloflutter-dd552.firebaseapp.com',
    storageBucket: 'helloflutter-dd552.firebasestorage.app',
  );

}